### ISSUE TITLE
It cannot work on node.js v7.2.1

### ISSUE THREAD

**Issue by n0rv1n** [JulianDuniec/express-controllers#18]
the express-controller@0.3.0 cannot work on node.js v7.2.1（windows）
btw:it works well on linux.
something wrong in lib/expressController.js

line 26：
file = file.replace(dirPath + '/', '');

should be changed to:
file = file.replace(dirPath + '/', '').replace(dirPath + '\\\\', '');

**Comment by JulianDuniec** [comment]
#19 Hi, please update to 0.3.1 for resolution of this issue. 

https://github.com/JulianDuniec/express-controllers/commit/7c8c3d27f46b62359f425ea779ecddc123b1226e

**Comment by n0rv1n** [comment]
thx :)
