### ISSUE TITLE
question: how do we leverage next and error handling?

### ISSUE THREAD

**Issue by angelxmoreno** [JulianDuniec/express-controllers#9]

**Comment by sandeepdas** [comment]
have the same query : how to use next and error handling

**Comment by slavik57** [comment]
Same here...
I would like to integrate it with passport but it does not have the next function

**Comment by sandeepdas** [comment]
I did some changes to the module and sent it to across to Julian for leveraging next chaining, awating to hear back..

**Comment by angelxmoreno** [comment]
good to know

**Comment by JulianDuniec** [comment]
Hi @sandeepdas ! Could you please submit a pull request with the changes, so that I can review them? 

Cheers
/J

**Comment by sandeepdas** [comment]
@JulianDuniec , have submitted the pull request
